### ISSUE TITLE
OpenLayers site broken

### ISSUE THREAD

**Issue by mj1856** [dosx/timezone-picker#13]
http://scratch.andrewl.in/timezone-picker/example_site/openlayers_example.html

![image](https://f.cloud.github.com/assets/1396388/2112545/3b2aa53c-9020-11e3-93dc-228fd24b0051.png)

**Comment by JasonTheProgrammer** [comment]
Tested on Windows 10, same result as depicted by mj1856 in:

- Chrome 51
- Firefox 46, 47
- IE 11.306
- Edge 25

**Comment by andrewlin12** [comment]
Well, it's been a while since I looked at this, but it seems like the OpenLayers WMS server that I was using doesn't work anymore. Changed it over to use OSM: https://github.com/dosx/timezone-picker/commit/2f43eb49092360127d64376e814bfe138cdedb78
