### ISSUE TITLE
Update map data

### ISSUE THREAD

**Issue by mj1856** [dosx/timezone-picker#16]
tz_world has been updated a few times to deal with new time zones and border changes.  Please update to the current version.  Thanks.

**Comment by ishirav** [comment]
+1
For example, Asia/Urumqi is UTC+6 and not UTC+8.
Regenerating tz_json solves this problem.

**Comment by andrewlin12** [comment]
Wow, my script still works. Amazing.

**Comment by mattjohnsonpint** [comment]
Very nice. :)  Also, better maps are now available at https://github.com/evansiroky/timezone-boundary-builder if you are interested in updating. :)
